Add-WindowsFeature Net-Framework-Features -Source D:\sources\sxs
Add-WindowsFeature Web-Server,Web-WebServer -Source D:\sources\sxs
Add-WindowsFeature Web-Common-Http -Source D:\sources\sxs
Add-WindowsFeature Web-Static-Content,Web-Default-Doc -Source D:\sources\sxs
Add-WindowsFeature Web-Dir-Browsing -Source D:\sources\sxs
Add-WindowsFeature Web-Http-Errors -Source D:\sources\sxs
Add-WindowsFeature Web-App-Dev -Source D:\sources\sxs
Add-WindowsFeature Web-Asp-Net -Source D:\sources\sxs
Add-WindowsFeature Web-Net-Ext -Source D:\sources\sxs
Add-WindowsFeature Web-ISAPI-Ext -Source D:\sources\sxs
Add-WindowsFeature Web-ISAPI-Filter -Source D:\sources\sxs
Add-WindowsFeature Web-Health -Source D:\sources\sxs
Add-WindowsFeature Web-Http-Logging -Source D:\sources\sxs
Add-WindowsFeature Web-Log-Libraries -Source D:\sources\sxs
Add-WindowsFeature Web-Request-Monitor -Source D:\sources\sxs
Add-WindowsFeature Web-Http-Tracing -Source D:\sources\sxs
Add-WindowsFeature Web-Security -Source D:\sources\sxs
Add-WindowsFeature Web-Basic-Auth -Source D:\sources\sxs
Add-WindowsFeature Web-Windows-Auth -Source D:\sources\sxs
Add-WindowsFeature Web-Filtering -Source D:\sources\sxs
Add-WindowsFeature Web-Digest-Auth -Source D:\sources\sxs
Add-WindowsFeature Web-Performance -Source D:\sources\sxs
Add-WindowsFeature Web-Stat-Compression -Source D:\sources\sxs
Add-WindowsFeature Web-Dyn-Compression -Source D:\sources\sxs
Add-WindowsFeature Web-Mgmt-Tools -Source D:\sources\sxs
Add-WindowsFeature Web-Mgmt-Console -Source D:\sources\sxs
Add-WindowsFeature Web-Mgmt-Compat -Source D:\sources\sxs
Add-WindowsFeature Web-Metabase -Source D:\sources\sxs
Add-WindowsFeature Application-Server -Source D:\sources\sxs
Add-WindowsFeature AS-Web-Support -Source D:\sources\sxs
Add-WindowsFeature AS-TCP-Port-Sharing -Source D:\sources\sxs
Add-WindowsFeature AS-WAS-Support -Source D:\sources\sxs 
Add-WindowsFeature AS-HTTP-Activation -Source D:\sources\sxs
Add-WindowsFeature AS-TCP-Activation -Source D:\sources\sxs
Add-WindowsFeature AS-Named-Pipes -Source D:\sources\sxs
Add-WindowsFeature AS-Net-Framework -Source D:\sources\sxs
Add-WindowsFeature WAS -Source D:\sources\sxs
Add-WindowsFeature WAS-Process-Model -Source D:\sources\sxs
Add-WindowsFeature WAS-NET-Environment -Source D:\sources\sxs
Add-WindowsFeature WAS-Config-APIs -Source D:\sources\sxs
Add-WindowsFeature Web-Lgcy-Scripting -Source D:\sources\sxs
Add-WindowsFeature Windows-Identity-Foundation -Source D:\sources\sxs
Add-WindowsFeature Server-Media-Foundation -Source D:\sources\sxs
Add-WindowsFeature Xps-Viewer -Source D:\sources\sxs
